// UI chrome strings only. All *answer* content is generated by the LLM in the user's language.
// ponytail: plain object, no i18n library for 3 languages of static chrome.
export type Lang = "en" | "ru" | "fr";
export const LANGS: { code: Lang; label: string }[] = [
  { code: "en", label: "English" },
  { code: "ru", label: "Русский" },
  { code: "fr", label: "Français" },
];

export const t = {
  en: {
    title: "Olim Navigator",
    tagline: "Israeli bureaucracy, explained in your language.",
    start: "Start", next: "Next", skip: "Skip quiz",
    discoveries: "Things you might be missing",
    askPlaceholder: "Ask about any Israeli bureaucracy…",
    send: "Send", uploadLetter: "Explain a Hebrew letter (photo)",
    groundedIn: "Grounded in", helpful: "Helpful", notHelpful: "Not helpful", tooSlow: "Too slow", thanksFeedback: "Thanks",
    capReached: "You've hit today's free question limit. Come back tomorrow 🙏",
    globalCap: "We're at capacity for today — please come back tomorrow 🙏",
    thinking: "Thinking…",
  },
  ru: {
    title: "Olim Navigator",
    tagline: "Израильская бюрократия — на вашем языке.",
    start: "Начать", next: "Далее", skip: "Пропустить",
    discoveries: "Что вы могли упустить",
    askPlaceholder: "Спросите об израильской бюрократии…",
    send: "Отправить", uploadLetter: "Объяснить письмо на иврите (фото)",
    groundedIn: "Источник", helpful: "Полезно", notHelpful: "Не помогло", tooSlow: "Медленно", thanksFeedback: "Спасибо",
    capReached: "Дневной лимит бесплатных вопросов исчерпан. Возвращайтесь завтра 🙏",
    globalCap: "Мы перегружены сегодня — зайдите завтра 🙏",
    thinking: "Думаю…",
  },
  fr: {
    title: "Olim Navigator",
    tagline: "La bureaucratie israélienne, expliquée dans votre langue.",
    start: "Commencer", next: "Suivant", skip: "Passer",
    discoveries: "Ce qui pourrait vous échapper",
    askPlaceholder: "Posez une question sur la bureaucratie israélienne…",
    send: "Envoyer", uploadLetter: "Expliquer une lettre en hébreu (photo)",
    groundedIn: "Basé sur", helpful: "Utile", notHelpful: "Pas utile", tooSlow: "Trop lent", thanksFeedback: "Merci",
    capReached: "Limite quotidienne atteinte. Revenez demain 🙏",
    globalCap: "Nous sommes à pleine capacité aujourd'hui — revenez demain 🙏",
    thinking: "Réflexion…",
  },
} satisfies Record<Lang, Record<string, string>>;
